name: "Install Keptn"
description: "Install Keptn inside a Kubernetes context"
inputs: 
  KEPTN_VERSION:   
    description: "The version of Keptn that should be installed (e.g. 0.13.1)"
    required: true
outputs:
  KEPTN_ENDPOINT:
    description:  URI of the Keptn endpoint that can be used to communicate with Keptn
    value: ${{ steps.ouput_keptn_env.outputs.KEPTN_ENDPOINT }}
  KEPTN_API_TOKEN:
    description: A API token needed for the communication with Keptn
    value: ${{ steps.ouput_keptn_env.outputs.KEPTN_API_TOKEN }}
runs:
  using: "composite"
  steps:
    - name: "Download & Install Keptn binary"
      shell: "bash"
      with:
        KEPTN_VERSION: ${{ inputs.KEPTN_VERSION }}
      run:
        - "curl -sL https://get.keptn.sh | bash"
    - name: "Install Keptn in cluster"
      shell: bash
      run:
        - "keptn install --endpoint-service-type=LoadBalancer --use-case=continuous-delivery"
    - name: "Authenticate Keptn CLI"
      shell: bash
      run:
        - "keptn auth"
    - name: "Output Keptn environment"
      id: ouput_keptn_env
      shell: "bash"
      run: |
        api_token=$(keptn auth --export | sed -nr  's/API Token:\s+(.*)/\1/p')
        endpoint=$(keptn auth --export | sed -nr 's/Endpoint:\s+(.*)/\1/p')
        echo "::add-mask::$api_token"
        echo "::set-output name=KEPTN_API_TOKEN::$api_token"
        echo "::set-output name=KEPTN_ENDPOINT::$endpoint"
